Input_lab_results_set2_some_abnormal_results = {
        'sodium': (143),
        'potassium': (4.5),
        'chloride': (96.0),
        'bicarbonate': (24),
        'bun': (23), 
        'creatinine': (1.1),
        'glucose': (126),
        'calciun':( 8.7),
        'magnesium':(1.4),
        'phosphorus':( 3.6),
        'whitecellcount':(13.4),
        'hemoglobin':(33.4),
        'hematocrit':(39),
        'platelets': ( 80),
        'tsh':(2.2),
        'a1c':(6.6),
        }

Input_lab_results_set1_all_normal_results = {
        'sodium': (143),
        'potassium': (4.5),
        'chloride': (96.0),
        'bicarbonate': (24),
        'bun': (23), 
        'creatinine': (1.1),
        'glucose': (106),
        'calciun':( 8.7),
        'magnesium':(1.8),
        'phosphorus':( 3.6),
        'whitecellcount':(10.4),
        'hemoglobin':(14.4),
        'hematocrit':(40),
        'platelets': ( 170),
        'tsh':(2.2),
        'a1c':(5.6),
        }

Input_lab_results_set3_critical_results = {
        'sodium': (143),
        'potassium': (6.5),
        'chloride': (96.0),
        'bicarbonate': (24),
        'bun': (111), 
        'creatinine': (1.1),
        'glucose': (106),
        'calciun':( 8.7),
        'magnesium':(1.8),
        'phosphorus':( 3.6),
        'whitecellcount':(10.4),
        'hemoglobin':(34.4),
        'hematocrit':(40),
        'platelets': ( 870),
        'tsh':(2.5),
        'a1c':(5.6),
        }